"""Audience plates — one optimized door per buyer type."""
from __future__ import annotations

VELARU_PUBLIC = "https://velaru.xyz"

# slug → plate config
PLATES: dict[str, dict] = {
    "developers": {
        "emoji": "⌨️",
        "title": "Developers",
        "headline": "Can this agent still act right now?",
        "subhead": "Metered fuse hop API. DEAD → verdict:false + verify URL. Ship in one curl.",
        "pain": "You're building agent loops without a kill switch that strangers can verify.",
        "offer": "Free API key · 1,000 hops/mo · Pro at $99/mo",
        "price": "From $0",
        "cta_label": "Get free API key",
        "cta_route": "signup",
        "secondary_label": "Read docs",
        "secondary_route": "docs",
        "proof": "Live hop demo on homepage · openapi.json",
        "tags": ["api", "curl", "hn", "plg"],
    },
    "agents": {
        "emoji": "🤖",
        "title": "Agent builders",
        "headline": "Pre-exec gate for autonomous agents",
        "subhead": "Hop before commit. Fail closed on DEAD. Receipt every action — MCP-ready.",
        "pain": "Your agent can still act after you thought you killed it.",
        "offer": "Gate API + /.well-known/gate.json discovery",
        "price": "From $0",
        "cta_label": "Get API key",
        "cta_route": "signup",
        "secondary_label": "Agent manifest",
        "secondary_href": "/.well-known/gate.json",
        "proof": "POST /v1/fuse/hop → verify_url in response",
        "tags": ["mcp", "x402", "agents", "kill-switch"],
    },
    "startups": {
        "emoji": "🚀",
        "title": "Startups",
        "headline": "48hr agent fuse install",
        "subhead": "We wire your stack. You demo DEAD fail-closed to investors this week.",
        "pain": "You need proof of control before the board meeting — not another sprint of infra.",
        "offer": "One agent path wired + handoff call + Pro month included",
        "price": "$2,500",
        "cta_label": "Book install slot",
        "cta_route": "install",
        "secondary_label": "DIY free tier",
        "secondary_route": "signup",
        "proof": "Live DEAD → verify demo on delivery",
        "tags": ["install", "speed", "fundraise"],
    },
    "legal": {
        "emoji": "⚖️",
        "title": "Legal & GC",
        "headline": "Prove the agent could not act when you said it couldn't",
        "subhead": "Stranger verify at /verify — no login, no trust-me dashboard.",
        "pain": "Board asks for proof. You have logs. They want independent verification.",
        "offer": "Bind Room assessment · pattern + gate export before bind",
        "price": "$1,750 due now",
        "cta_label": "Start Bind Room",
        "cta_route": "bind_room",
        "secondary_label": "Officer pack JSON",
        "secondary_href": "/bind-room/officer-pack.json",
        "proof": "Officer pack (SERFF-shaped) + appendix verify permalinks. Do not lead with FRE to a CUO.",
        "tags": ["gc", "fre707", "exhibit", "court"],
    },
    "compliance": {
        "emoji": "📋",
        "title": "Compliance officers",
        "headline": "NAIC / EU Art 12 decision-point receipts",
        "subhead": "Signed receipts at the moment of agent action — not a quarterly PDF.",
        "pain": "Regulators want proof at decision time. You have policy docs from last year.",
        "offer": "Exhibit D pack · Art 12 checklist · session receipts",
        "price": "Assessment from $3,500",
        "cta_label": "Run compliance scan",
        "cta_href": f"{VELARU_PUBLIC}/check",
        "secondary_label": "Exhibit D",
        "secondary_href": f"{VELARU_PUBLIC}/check",
        "proof": "NAIC AI Evaluation Tool clocks · Aug 2026 deadlines",
        "tags": ["naic", "eu-ai-act", "art12", "audit"],
    },
    "carriers": {
        "emoji": "🏦",
        "title": "Carriers & PAS",
        "headline": "Bind ALLOW/BLOCK with a receipt legal can open",
        "subhead": "Same hop family as PAS bind-check. PERMIT/DENY before irreversible commit.",
        "pain": "Bind went through on an agent you can't prove was live.",
        "offer": "Bind Room officer pack + PolicyCenter pre-bind weld. Control, not a rating model.",
        "price": "$1,750 Bind Room · $2,500 48hr weld",
        "cta_label": "Open Bind Room",
        "cta_route": "bind_room",
        "secondary_label": "PolicyCenter weld",
        "secondary_href": "/v1/pas/policycenter/pre-bind",
        "proof": "BLOCK → restraint receipt → stranger verify",
        "tags": ["insurance", "bind", "pas", "guidewire"],
    },
    "brokers": {
        "emoji": "📄",
        "title": "Brokers & MGAs",
        "headline": "CG 40 / 47 renewal with proof rail",
        "subhead": "Renewal desk gets verify links — not another AI trust slide deck.",
        "pain": "Carrier wants AI controls proof at renewal. Your insured has nothing clickable.",
        "offer": "MGA delegated-authority gate — premium/line/state + fuse hop before binder",
        "price": "$2,500 48hr weld · fastest yes",
        "cta_label": "MGA / Bind Room",
        "cta_route": "bind_room",
        "secondary_label": "48hr weld",
        "secondary_route": "install",
        "proof": "Independent verify · prepaid mortality fuse",
        "tags": ["broker", "renewal", "cg4047"],
    },
    "enterprise": {
        "emoji": "🏢",
        "title": "Enterprise",
        "headline": "One org mortality root — children cannot outlive parent",
        "subhead": "Prepaid fuse tree. DEAD propagates fail-closed across delegated agents.",
        "pain": "Every team built their own kill switch. None of them verify the same way.",
        "offer": "Org reactor · bind rooms · on-prem option",
        "price": "$80–150K/yr",
        "cta_label": "Enterprise inquiry",
        "cta_mailto": "subject=Enterprise%20%E2%80%94%20Org%20reactor",
        "secondary_label": "Trust & limits",
        "secondary_route": "trust",
        "proof": "Patent #64/124,027 · hash-chained receipts",
        "tags": ["enterprise", "procurement", "soc2-path"],
    },
    "boards": {
        "emoji": "🎯",
        "title": "Boards & directors",
        "headline": "Show the fuse was DEAD — in one link",
        "subhead": "No AI literacy required. LIVE · ARMED · DEAD · UNSIGNED. Click verify.",
        "pain": "Director asks: 'Can it still run?' You need an answer in 30 seconds.",
        "offer": "Panic scan · board-ready verify permalink",
        "price": "CHARGE packs from $500",
        "cta_label": "Run public check",
        "cta_href": f"{VELARU_PUBLIC}/check",
        "secondary_label": "Trust limits",
        "secondary_route": "trust",
        "proof": "Stranger verify free · fail-closed hop",
        "tags": ["board", "directors", "panic", "governance"],
    },
    "defense": {
        "emoji": "🛡️",
        "title": "Defense & gov",
        "headline": "Agent existence proof under DoD 3000.09 pressure",
        "subhead": "Pre-exec gate with signed restraint receipts — not resurrection from UI.",
        "pain": "Delegated autonomy without public existence proof fails closed.",
        "offer": "Execute-gate · SCITT/AIR export · assessment",
        "price": "Custom",
        "cta_label": "Defense inquiry",
        "cta_mailto": "subject=Defense%20%E2%80%94%20Agent%20fuse",
        "secondary_label": "Public check",
        "secondary_href": f"{VELARU_PUBLIC}/check",
        "proof": "Fail-closed DEAD · independent verify",
        "tags": ["dod", "3000.09", "defense", "gov"],
    },
    "hiring": {
        "emoji": "👔",
        "title": "HR & hiring tech",
        "headline": "Connecticut AEDT hiring proof — Oct 2027 clock",
        "subhead": "Classify + seal hiring decisions with stranger-verifiable receipts.",
        "pain": "AEDT audit asks what the agent decided and when. Spreadsheets won't cut it.",
        "offer": "Hiring domain classify · signed receipt · verify URL",
        "price": "Gate Pro + assessment",
        "cta_label": "Try hiring classify",
        "cta_route": "signup",
        "secondary_label": "CT compliance",
        "secondary_href": f"{VELARU_PUBLIC}/check",
        "proof": "velaru hiring domain · receipt per decision",
        "tags": ["hiring", "aedt", "connecticut", "hr"],
    },
    "consumers": {
        "emoji": "✊",
        "title": "Consumers",
        "headline": "Document AI harm with cryptographic proof",
        "subhead": "Mishara — plain English + Velaru-signed receipt for platforms and agencies.",
        "pain": "Platform wronged you. You need evidence stronger than screenshots.",
        "offer": "Harm intake · demand letter · verify link",
        "price": "Free intake",
        "cta_label": "Open Mishara",
        "cta_href": "https://mishara.onrender.com",
        "secondary_label": "Verify engine",
        "secondary_href": f"{VELARU_PUBLIC}/verify",
        "proof": "Independent audit receipt · Exhibit A hash",
        "tags": ["consumer", "rights", "mishara"],
    },
    "investors": {
        "emoji": "📈",
        "title": "Investors",
        "headline": "Prepaid mortality fuse — infrastructure, not wrapper",
        "subhead": "Metered Gate API + whale panic SKUs + patent-pending proof rail.",
        "pain": "Another 'AI safety' slide deck with no fail-closed demo.",
        "offer": "Live metrics · deck · status page",
        "price": "Revenue: Gate + Velaru SKUs",
        "cta_label": "View status",
        "cta_route": "status_page",
        "secondary_label": "Live demo",
        "secondary_route": "index",
        "proof": "Patent #64/124,027 · public verify · hop meter",
        "tags": ["investor", "deck", "metrics"],
    },
    "partners": {
        "emoji": "🔗",
        "title": "Integrators & partners",
        "headline": "White-label fuse hop under your brand",
        "subhead": "Gate meters. Velaru proves. You keep the customer relationship.",
        "pain": "Your clients want agent kill switches. You don't want to build the proof rail.",
        "offer": "Partner install · rev share · API proxy",
        "price": "From $2,500/install",
        "cta_label": "Partner install",
        "cta_route": "install",
        "secondary_label": "Partner email",
        "secondary_mailto": "subject=Partner%20%E2%80%94%20White%20label",
        "proof": "Gate 402 meter · Velaru verify chain",
        "tags": ["partner", "whitelabel", "agency"],
    },
}


def all_plates() -> dict[str, dict]:
    return PLATES


def get_plate(slug: str) -> dict | None:
    return PLATES.get(slug)


def plate_list() -> list[dict]:
    items = []
    for slug, p in PLATES.items():
        items.append({"slug": slug, **p})
    return items


def opportunities_manifest(public_url: str, contact_email: str) -> dict:
    entries = []
    for slug, p in PLATES.items():
        entries.append(
            {
                "slug": slug,
                "title": p["title"],
                "headline": p["headline"],
                "price": p["price"],
                "url": f"{public_url}/for/{slug}",
                "pitch_url": f"{public_url}/pitch/{slug}",
                "tags": p.get("tags", []),
            }
        )
    return {
        "name": "Gate + Velaru opportunity surfaces",
        "version": "1.0.0",
        "hub": f"{public_url}/start",
        "opportunities": entries,
        "contact": contact_email,
        "engine": VELARU_PUBLIC,
    }
