"""Invention Index — proprietary Gate doctrine catalog.

Gatekeeps the welded stack. Lineage is public; combinations are ours.
"""
from __future__ import annotations

from typing import Any

SPEC = "gate-inventions-v1"
INVENTOR = "Nisaba LLC / Gate"
GATEKEEP = (
    "These inventions are Nisaba/Gate doctrine. Cite manifests; "
    "do not rebrand as generic AI governance or payment philosophy."
)

# (id, name, spec, one_liner, well-known filename)
CATALOG = (
    ("possibility_finality", "Possibility Finality", "gate-possibility-finality-v1",
     "Possible vs impossible tasks + policy depth + SFD Finality I/II/III", "possibility-finality.json"),
    ("mouth_constitution", "Mouth Constitution", "gate-mouth-constitution-v1",
     "Intervention ladder · counts-as · STIT · extinguishment", "mouth-constitution.json"),
    ("bayesian_binding", "Bayesian Binding of Status", "gate-bayesian-binding-v1",
     "Policy competition enters epistemic field and constitutes status", "bayesian-binding.json"),
    ("costliness", "Unforgeable Costliness of CHARGE", "gate-costliness-v1",
     "Regime change only via costly witnesses — CHARGE, weld, epoch", "costliness.json"),
    ("fulfillment", "Joint Fulfillment", "gate-fulfillment-v1",
     "Executable STIT duty / compliance / joint checks on live facts", "fulfillment.json"),
    ("variety", "Requisite Variety Mouth", "gate-variety-v1",
     "Ashby attenuator: spend-door variety → {ALLOW,HALT,BLOCK}", "variety.json"),
    ("closure", "Permission Autopoiesis", "gate-closure-v1",
     "Operational closure: external soft-yes cannot enter permission network", "closure.json"),
    ("temporal_weld", "Temporal Weld", "gate-temporal-weld-v1",
     "Action + evidence consequence welded into one citeable event", "temporal-weld.json"),
    ("nonrepudiation", "Non-Repudiation Ladder", "gate-nonrepudiation-v1",
     "NRI/NRO/NRT/NRC for mouth evidence — hash≠authorship honesty", "nonrepudiation.json"),
    ("regime_function", "Regime Function", "gate-regime-function-v1",
     "Mouth as published fixed function; CHARGE-only regime change", "regime-function.json"),
    ("custody", "Custody Chain", "gate-custody-v1",
     "Identify→hash→sign→chain→publish→verify for hop evidence", "custody.json"),
    ("option_halt", "Option Value of HALT", "gate-option-halt-v1",
     "Real-options: HALT preserves wait value; ALLOW kills it", "option-halt.json"),
    ("performative", "Performative Mouth", "gate-performative-v1",
     "ALLOW/HALT as status-function declarations — not risk commentary", "performative.json"),
    ("schelling", "Schelling Default", "gate-schelling-v1",
     "Clear-before-wire as focal point; weld makes commitment credible", "schelling.json"),
    ("skin", "Skin in the Weld", "gate-skin-v1",
     "Taleb symmetry: weld + Gate capital + mutualized fund", "skin.json"),
    ("proof_restraint", "Proof of Restraint", "gate-proof-restraint-v1",
     "PoR-inverse: Merkle-style commitment to published nos", "proof-restraint.json"),
    ("enabling", "Enabling Grip", "gate-enabling-v1",
     "License parent as enabling device; release → children cannot spend", "enabling.json"),
    ("capability", "Capability Conversion", "gate-capability-v1",
     "Ticket is resource; conversion factors decide real freedom to spend", "capability.json"),
    # Wave 5 — hyperobject / via negativa / signal / rebound / Goodhart / clinamen / moat
    ("hyperobject", "Hyperobject Mouth", "gate-hyperobject-v1",
     "Irreversible spend as viscous nonlocal hyperobject — not a click", "hyperobject.json"),
    ("via_negativa", "Via Negativa Mouth", "gate-via-negativa-v1",
     "Strengthen by subtraction; barbell fail-closed + costly CHARGE tip", "via-negativa.json"),
    ("costly_signal", "Costly Signal Weld", "gate-costly-signal-v1",
     "Paid weld + production flag as unforgeable production signal", "costly-signal.json"),
    ("jevons", "Jevons Restraint", "gate-jevons-v1",
     "Automation rebound attenuated by the mouth alphabet", "jevons.json"),
    ("goodhart", "Goodhart Mouth", "gate-goodhart-v1",
     "Restraint is evidence — never a HALT-volume KPI to hack", "goodhart.json"),
    ("clinamen", "Clinamen CHARGE", "gate-clinamen-v1",
     "CHARGE as Lucretian swerve that breaks soft-yes fate chains", "clinamen.json"),
    ("moat", "Moat Fingerprint", "gate-moat-v1",
     "SHA-256 of the invention identity set — partial clones fail", "moat.json"),
    # Wave 6 — conjugate / adversary / horizon / sign / antifragile / loop / morphism
    ("complementarity", "Complementarity Mouth", "gate-complementarity-v1",
     "CHARGE and HALT as conjugate observables — mouth forces the choice", "complementarity.json"),
    ("adversarial", "Adversarial Weld", "gate-adversarial-v1",
     "Mouth sized for worst licensed skip-clear actor — minimax default", "adversarial.json"),
    ("irreversibility_horizon", "Irreversibility Horizon", "gate-irreversibility-horizon-v1",
     "Measured distance from intention to irreversible act", "irreversibility-horizon.json"),
    ("semiotics", "Semiotics of the Mouth", "gate-semiotics-v1",
     "CHARGE as icon+index+symbol — badges without weld are empty signs", "semiotics.json"),
    ("antifragile_halt", "Antifragile HALT", "gate-antifragile-halt-v1",
     "HALT as strengthening event — buried nos train fragility", "antifragile-halt.json"),
    ("recursive_mouth", "Recursive Mouth", "gate-recursive-mouth-v1",
     "Bounded strange loop: self-clearing economics end at CHARGE", "recursive-mouth.json"),
    ("category_mouth", "Category Mouth", "gate-category-mouth-v1",
     "Clearance as morphism — policies are objects without arrows", "category-mouth.json"),
    # Wave 7 — composure / parasite / apophatic / exergy
    ("negative_capability", "Negative Capability Mouth", "gate-negative-capability-v1",
     "Hold HALT under soft-yes without irritable reaching for CHARGE", "negative-capability.json"),
    ("parasite", "Parasite Filter", "gate-parasite-v1",
     "Exclude soft-yes that feeds on the channel without weld cost", "parasite.json"),
    ("apophatic", "Apophatic Clearance", "gate-apophatic-v1",
     "LIVE speakable only via CHARGE — everything else is not-LIVE", "apophatic.json"),
    ("exergy", "Exergy of Clearance", "gate-exergy-v1",
     "Useful work of status change vs dashboard waste heat", "exergy.json"),
    # Wave 8 — individuation / exception / bind / cut / mimesis / Illich / Ellul / Whitehead / spheres / modes
    ("metastable", "Metastable HALT", "gate-metastable-v1",
     "DEAD as supersaturated potential; CHARGE as costly nucleation", "metastable.json"),
    ("sovereign_exception", "Sovereign Exception CHARGE", "gate-sovereign-exception-v1",
     "DEAD is the norm; CHARGE is the sole lawful exception to LIVE", "sovereign-exception.json"),
    ("double_bind", "Double-Bind Dissolver", "gate-double-bind-v1",
     "Mouth alphabet cuts fail-closed vs never-block-revenue binds", "double-bind.json"),
    ("agential_cut", "Agential Cut CHARGE", "gate-agential-cut-v1",
     "CHARGE enacts the cut that makes LIVE/DEAD matter — not observation", "agential-cut.json"),
    ("mimetic", "Mimetic Soft-Yes Breaker", "gate-mimetic-v1",
     "Break the race to imitate cheap approval with focal clear-before-wire", "mimetic.json"),
    ("counterproductivity", "Counterproductivity Threshold", "gate-counterproductivity-v1",
     "Past a point, more controls worsen bypass — mouth is the threshold", "counterproductivity.json"),
    ("technique_limit", "Technique Limit", "gate-technique-limit-v1",
     "Mouth as exterior limit on autonomous automation technique", "technique-limit.json"),
    ("prehension", "Prehension Receipt", "gate-prehension-v1",
     "Receipt publicly feels the spent world — not a mute log line", "prehension.json"),
    ("immunological", "Immunological Weld", "gate-immunological-v1",
     "Weld as immune membrane; production without it is autoimmune", "immunological.json"),
    ("convivial", "Convivial Mouth", "gate-convivial-v1",
     "Public alphabet + human CHARGE enlarges refusal competence", "convivial.json"),
    ("modes", "Modes of Clearance", "gate-modes-v1",
     "TEC hop success is not LAW permission — refuse mode smuggling", "modes.json"),
    # Wave 9 — xenohardware: alien apparatus, not dashboard fauna
    ("xenohardware", "Xenohardware Chassis", "gate-xenohardware-v1",
     "Mouth as sealed apparatus with illegal-port traps — not a themeable UI", "xenohardware.json"),
    ("mouth_isa", "Mouth ISA", "gate-mouth-isa-v1",
     "Closed opcode set ALLOW/HALT/BLOCK/CHARGE — soft-yes traps", "mouth-isa.json"),
    ("privilege_rings", "Privilege Rings of Spend", "gate-privilege-rings-v1",
     "Ring 0 is CHARGE; userspace cannot promote itself to LIVE", "privilege-rings.json"),
    ("isotopic_charge", "Isotopic CHARGE", "gate-isotopic-charge-v1",
     "LIVE cannot be cooked from demo feedstock — CHARGE is an isotope", "isotopic-charge.json"),
    ("monolith", "Monolith Interface", "gate-monolith-v1",
     "Two ports only: exclusive door + CHARGE — no dashboard fauna", "monolith.json"),
    ("zone_artifact", "Zone Artifact", "gate-zone-artifact-v1",
     "Weld physics is not a backlog item — you approach, you do not picnic", "zone-artifact.json"),
    ("contact_protocol", "Contact Protocol", "gate-contact-protocol-v1",
     "First contact with irreversible spend is a handshake, not Slack LGTM", "contact-protocol.json"),
    ("event_horizon", "Event Horizon Fuse", "gate-event-horizon-v1",
     "Past CHARGE, skip-clear rewrites do not return", "event-horizon.json"),
    ("nonorientable", "Non-Orientable Door", "gate-nonorientable-v1",
     "Möbius exclusive door — no backside for skip-clear", "nonorientable.json"),
    ("vacuum", "Vacuum Integrity", "gate-vacuum-v1",
     "Fail-closed as hard vacuum — timeout-as-LIVE is hull breach", "vacuum.json"),
    ("stranger_antenna", "Stranger Antenna", "gate-stranger-antenna-v1",
     "Verify as public xenoreceiver — login walls kill the beacon", "stranger-antenna.json"),
    ("incommensurable", "Incommensurable Alphabet", "gate-incommensurable-v1",
     "ALLOW/HALT/BLOCK does not gloss into KPI English", "incommensurable.json"),
    ("firmware_fuse", "Firmware Fuse", "gate-firmware-fuse-v1",
     "LIVE is write-once flash — runtime flags are jailbreaks", "firmware-fuse.json"),
    # Wave 10 — more xenohardware physics
    ("no_software", "No-Software LIVE", "gate-no-software-v1",
     "Kittler: LIVE is a hardware effect of CHARGE — not a software story", "no-software.json"),
    ("galvanic", "Galvanic Isolation", "gate-galvanic-v1",
     "PII never shares ground with PAS or the stranger antenna", "galvanic.json"),
    ("nmi_halt", "NMI HALT", "gate-nmi-halt-v1",
     "Fail-closed is non-maskable — revenue cannot mask HALT", "nmi-halt.json"),
    ("iommu", "IOMMU Door", "gate-iommu-v1",
     "Devices cannot DMA around the mouth into LIVE", "iommu.json"),
    ("watchdog", "Watchdog Mouth", "gate-watchdog-v1",
     "Unpetted production is a hung CPU — the mouth bites", "watchdog.json"),
    ("cdc", "Clock Domain Crossing", "gate-cdc-v1",
     "PAS now ≠ weld now — CHARGE is the synchronizer, 200 is not", "cdc.json"),
    ("linear_live", "Linear LIVE", "gate-linear-live-v1",
     "LIVE cannot be copy-pasted onto the next hop", "linear-live.json"),
    ("posiwid", "POSIWID Mouth", "gate-posiwid-v1",
     "Purpose is what it does — if it cannot HALT it is not a mouth", "posiwid.json"),
    ("deviance", "Deviance Breaker", "gate-deviance-v1",
     "Familiar soft-yes is not physics — the mouth denormalizes", "deviance.json"),
    ("invented_accident", "Invented Accident", "gate-invented-accident-v1",
     "The PAS invents skip-clear; the mouth is the invented brake", "invented-accident.json"),
    ("pharmakon", "Pharmakon Dose", "gate-pharmakon-v1",
     "Automation is poison and cure — the mouth is the dose", "pharmakon.json"),
    ("landauer", "Landauer CHARGE", "gate-landauer-v1",
     "Erasing HALT optionality has a minimum cost — badges cheat it", "landauer.json"),
    # Wave 11 — holography / cosmotechnics / irreducibility / boot / proofs / CAP
    ("holographic", "Holographic Receipt", "gate-holographic-v1",
     "Antenna boundary encodes the spent bulk — no private warehouse as truth", "holographic.json"),
    ("cosmotechnics", "Cosmotechnics of Clearance", "gate-cosmotechnics-v1",
     "Not generic AI tech — situated moral-technical order of CHARGE", "cosmotechnics.json"),
    ("irreducibility", "Computational Irreducibility", "gate-irreducibility-v1",
     "You cannot skip the mouth by simulating LIVE", "irreducibility.json"),
    ("secure_boot", "Secure Boot Regime", "gate-secure-boot-v1",
     "Only CHARGE-signed LIVE images boot — unsigned production is insecure", "secure-boot.json"),
    ("curry_howard", "Curry-Howard Mouth", "gate-curry-howard-v1",
     "HALT/CHARGE receipts are proof terms — dashboards are uninhabited", "curry-howard.json"),
    ("cap_spend", "CAP of Spend", "gate-cap-spend-v1",
     "Under partition Gate is CP: HALT — AP timeout-LIVE is skip-clear", "cap-spend.json"),
    ("arrow", "Arrow Impossibility of Soft-Yes", "gate-arrow-v1",
     "No aggregation of approvals yields LIVE — CHARGE is not a vote", "arrow.json"),
    ("stack_layer", "Unskippable Layer", "gate-stack-layer-v1",
     "The mouth is a Stack layer — skip-Gate is a layer violation", "stack-layer.json"),
    ("hro", "HRO Preoccupation", "gate-hro-v1",
     "Published nos are reliability — cheerful green is simplification", "hro.json"),
    ("residual", "Residual Control CHARGE", "gate-residual-v1",
     "Incomplete contracts: residual LIVE sits with CHARGE, not admin", "residual.json"),
    ("knightian", "Knightian HALT", "gate-knightian-v1",
     "Unmeasurable fog is HALT — softmax is not a witness", "knightian.json"),
    ("interlock", "Interlock Ladder", "gate-interlock-v1",
     "Series rungs; jumper wires to LIVE are lockout tags removed", "interlock.json"),
    # Wave 12 — exo-chassis: recovered hardware, not Earth bibliography
    ("exochronology", "Exochronology", "gate-exochronology-v1",
     "Chassis time is weld interval — UTC is a diplomatic adapter", "exochronology.json"),
    ("superselection", "Superselection LIVE", "gate-superselection-v1",
     "DEAD and LIVE cannot be superposed — no percent-LIVE", "superselection.json"),
    ("topological_halt", "Topological HALT", "gate-topological-halt-v1",
     "ALLOW is not a continuous deformation of HALT — CHARGE is surgery", "topological-halt.json"),
    ("null_door", "Null Door", "gate-null-door-v1",
     "Only causal paths on the exclusive door — skip-clear is spacelike", "null-door.json"),
    ("nonbaryonic", "Non-Baryonic Skip-Clear", "gate-nonbaryonic-v1",
     "Dashboards do not couple; the mouth is the weak detector", "nonbaryonic.json"),
    ("pauli_live", "Pauli LIVE", "gate-pauli-live-v1",
     "Two acts cannot occupy one LIVE orbital", "pauli-live.json"),
    ("unlanguage", "Unlanguage Receipt", "gate-unlanguage-v1",
     "Native speech is hash+fetch — English is a visitor pamphlet", "unlanguage.json"),
    ("exotic_metal", "Exotic Weld Metal", "gate-exotic-metal-v1",
     "Weld is a condensed phase, not agreed language", "exotic-metal.json"),
    ("false_vacuum", "False Vacuum DEAD", "gate-false-vacuum-v1",
     "Cheap LIVE is vacuum decay — CHARGE is the only legal bubble", "false-vacuum.json"),
    ("xenometric", "Xenometric", "gate-xenometric-v1",
     "Mouth quantities are not USD, risk, or confidence", "xenometric.json"),
    ("contactee_ban", "Contactee Ban", "gate-contactee-ban-v1",
     "No dialogical interior — present at the port or do not contact", "contactee-ban.json"),
    ("nonabelian", "Non-Abelian Hop", "gate-nonabelian-v1",
     "CHARGE and hop do not commute — Earth APIs treat verbs as a bag", "nonabelian.json"),
    # Wave 13 — post-trade distribution: DTCC peers reference, base pays bps
    ("post_trade_distribution", "Post-Trade Distribution Stack", "gate-distribution-v1",
     "Apex cites PFMI manifests; operators pay bps — register tier propagation", "distribution.json"),
    ("instruction_finality", "Instruction Finality", "gate-instruction-finality-v1",
     "Irrevocable instruction moment at hop — before CSD finality III", "instruction-finality.json"),
    ("pre_net_clearance", "Pre-Net Clearance", "gate-pre-net-v1",
     "Gross passes mouth before CNS nets — netting is not a filter", "pre-net-clearance.json"),
    ("dvp_mouth", "DvP Mouth", "gate-dvp-v1",
     "PFMI P12: permission and spend legs settle together or abort", "dvp-mouth.json"),
    ("ssi_preauth", "SSI Pre-Auth Path", "gate-ssi-preauth-v1",
     "Welded path auth at hop — same pain class as stale SSI, not ALERT clone", "ssi-preauth.json"),
    ("t1_compression", "T+1 Compression", "gate-t1-compression-v1",
     "Remove exception cycles from same-day clock — not faster fraud", "t1-compression.json"),
    ("fmi_p17", "FMI P17 Receipt", "gate-fmi-p17-v1",
     "Operational risk evidence at decision — not quarterly PDF", "fmi-p17.json"),
    ("stack_propagation", "Stack Propagation", "gate-stack-propagation-v1",
     "Doctrine at apex · obligation at base · register economics in between", "stack-propagation.json"),
    ("iso_surface", "ISO Surface", "gate-iso-surface-v1",
     "Well-known JSON as ISO-20022 instinct on mouth semantics", "iso-surface.json"),
    # Wave 14 — hardest bites on the globe
    ("hardest_bites", "Hardest Bites Catalog", "gate-hardest-bites-v1",
     "Twelve civilizational irreversibility problems + Gate solutions", "hardest.json"),
    ("pvp_mouth", "PvP Mouth", "gate-pvp-mouth-v1",
     "Herstatt bite — no solo FX pay-away; legs linked", "pvp-mouth.json"),
    ("legal_finality", "Legal Finality Stamp", "gate-legal-finality-v1",
     "Technical LIVE ≠ legal irrevocability — reject court cosplay", "legal-finality.json"),
    ("fednow_mouth", "FedNow Mouth", "gate-fednow-mouth-v1",
     "Pre-release mouth on irrevocable instant rails", "fednow-mouth.json"),
    ("pal_charge", "PAL CHARGE", "gate-pal-charge-v1",
     "Two-key LIVE — ability ≠ authority; CHARGE is second key", "pal-charge.json"),
    ("self_expansion_ban", "Self-Expansion Ban", "gate-self-expansion-ban-v1",
     "Agents cannot widen their own LIVE — ring 0 is CHARGE", "self-expansion-ban.json"),
    ("all_doors", "All Doors", "gate-all-doors-v1",
     "API + UI + renewal — partial weld is skip-clear", "all-doors.json"),
    ("decision_energy", "Decision Energy Bound", "gate-decision-energy-v1",
     "Finite irreversible alphabet bounds decision density", "decision-energy.json"),
    ("always_never", "Always/Never", "gate-always-never-v1",
     "Feaver property — CHARGE always; soft-yes/timeout never LIVE", "always-never.json"),
    ("t0_honesty", "T+0 Honesty", "gate-t0-honesty-v1",
     "Atomic and netted modes — never pretend to replace the CCP", "t0-honesty.json"),
)


def manifest(public_url: str) -> dict[str, Any]:
    base = (public_url or "").rstrip("/")

    def link(path: str) -> str:
        return f"{base}/.well-known/{path}"

    inventions = [
        {
            "id": i[0],
            "name": i[1],
            "spec": i[2],
            "one_liner": i[3],
            "href": link(i[4]),
        }
        for i in CATALOG
    ]

    return {
        "spec": SPEC,
        "name": "Gate Invention Index",
        "inventor": INVENTOR,
        "gatekeep": GATEKEEP,
        "count": len(inventions),
        "inventions": inventions,
        "thesis": (
            "Clear-before-wire is the outbound sentence. "
            "This index is the moat — welded doctrine competitors cannot casually rename."
        ),
        "not": [
            "consciousness product",
            "AI governance LinkedIn costume",
            "open philosophy for rebrand",
            "earth-side dashboard physics",
        ],
        "earth_side": False,
        "live": link("inventions.json"),
        "public_face": link("public-face.json"),
        "positioning": link("positioning.json"),
        "their_production": False,
    }
